-- Run as ZMEM on zmemory-adb (Oracle 23ai).
-- Loads a 384-dim ONNX sentence-embedding model in-DB so embeddings are
-- generated by the database itself (no external embedding service).
--
-- Model is all-MiniLM-L6-v2 (384-dim) -- the SAME model the client-side
-- fastembed fallback uses (src/memory_core/embedder.py _MODEL_NAME). Do not
-- change this without re-running scripts/calibrate_embeddings.py: the two
-- runtimes must stay in the same vector space or cosine search breaks.
--
-- Prereq: export an Oracle-loadable ONNX build of all-MiniLM-L6-v2 (with
-- tokenizer + pooling metadata baked in, per Oracle's embedding-model
-- export guide) and stage it into a DB directory. Two options:
--   A) DBMS_CLOUD.GET_OBJECT from an object-storage URL you control:
--      BEGIN
--        DBMS_CLOUD.GET_OBJECT(
--          object_uri      => '&model_uri',           -- https://.../all_MiniLM_L6_v2.onnx
--          directory_name  => 'DATA_PUMP_DIR');
--      END;
--      /
--   B) Upload via SQL Developer Web / Database Actions into DATA_PUMP_DIR.
--
-- Then load it:
BEGIN
  DBMS_VECTOR.LOAD_ONNX_MODEL(
    directory  => 'DATA_PUMP_DIR',
    file_name  => 'all_MiniLM_L6_v2.onnx',
    model_name => 'ZMEM_EMBED',
    metadata   => JSON('{
        "function"   : "embedding",
        "embeddingOutput" : "embedding",
        "input"      : { "input": ["DATA"] }
    }'));
END;
/

-- Smoke test: should return a VECTOR with 384 dimensions.
SELECT VECTOR_EMBEDDING(ZMEM_EMBED USING 'hello world' AS data) AS v FROM dual;
