-- Run as ZMEM on zmemory-adb (Oracle 23ai).
-- Loads a 384-dim ONNX sentence-embedding model in-DB so embeddings are
-- generated by the database itself (no external embedding service).
--
-- Prereq: stage all_MiniLM_L12_v2.onnx into a DB directory. Two options:
--   A) DBMS_CLOUD.GET_OBJECT from an object-storage URL you control:
--      BEGIN
--        DBMS_CLOUD.GET_OBJECT(
--          object_uri      => '&model_uri',           -- https://.../all_MiniLM_L12_v2.onnx
--          directory_name  => 'DATA_PUMP_DIR');
--      END;
--      /
--   B) Upload via SQL Developer Web / Database Actions into DATA_PUMP_DIR.
--
-- Then load it:
BEGIN
  DBMS_VECTOR.LOAD_ONNX_MODEL(
    directory  => 'DATA_PUMP_DIR',
    file_name  => 'all_MiniLM_L12_v2.onnx',
    model_name => 'ZMEM_EMBED',
    metadata   => JSON('{
        "function"   : "embedding",
        "embeddingOutput" : "embedding",
        "input"      : { "input": ["DATA"] }
    }'));
END;
/

-- Smoke test: should return a VECTOR with 384 dimensions.
SELECT VECTOR_EMBEDDING(ZMEM_EMBED USING 'hello world' AS data) AS v FROM dual;
